blank_issues_enabled: false
contact_links:
  - name: â“ DÃºvidas / Perguntas
    url: https://github.com/dgadelha/Portugol-Webstudio/discussions/new?category=perguntas-respostas
    about: FaÃ§a perguntas sobre o uso da IDE, a linguagem Portugol ou qualquer outro assunto relacionado.
  - name: ğŸ’¡ Ideias e sugestÃµes
    url: https://github.com/dgadelha/Portugol-Webstudio/discussions/new?category=ideias-e-sugest%C3%B5es
    about: Compartilhe suas ideias e sugestÃµes para melhorar a IDE.
  - name: ğŸ’¬ Comunidade
    url: https://github.com/dgadelha/Portugol-Webstudio/discussions
    about: Participe de discussÃµes com outros usuÃ¡rios da IDE.
